### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lukastripp** [marcschmiedchen/home-assistant-wolf_ism8#11]
@marcschmiedchen  einfach toll, dass es noch implementiert wurde. Noch ein kurzes Feedback von mir.
Läuft alles tip top. Nur muss man erstmal verstehen, wenn man noch die alte Konfig hatte, dass diese raus muss aus der configuration.yaml. Danach klassisch einrichten. 
Bilder habe ich dir auch noch mal angehangen für vielleicht Doku Anpassung noch.

Kann man sich bei dir erkenntlich zeigen mit einer Paypal Spende oder ähnlichen? Ich finde, dass so etwas auch gewürdigt werden muss. Viele fordern immer nur und geben nichts. Kenne das leider viel zu oft. 

Hier noch der Tipp für andere:
Ich habe z.B. eine CGB-2 und das BM-2. 
Wenn man jetzt aber noch die Programme also Werte schreiben möchte, dann muss immer DKW mit ausgewählt werden.

Also für alle HA User, immer DKW & SYM mit auswählen. SYM kann auch manuell einen Datenpush - geniale Funktion.

![DKW](https://user-images.githubusercontent.com/95910433/222687642-00ed3214-6d1e-40e7-8797-cafaeb04eeb6.png)
![HG1](https://user-images.githubusercontent.com/95910433/222687645-1d6191a3-a712-4ed1-82ff-4f915cd1a4e0.png)
![SYM](https://user-images.githubusercontent.com/95910433/222687647-3fd2dccd-1ffa-4851-a2cc-1b8c3cccaae1.png)

**Comment by Dark-Tower-Coder** [comment]
Von mir auch vielen Dank für die klasse Integration!

**Comment by marcschmiedchen** [comment]
Hey leute danke fuer die Screenshots und die tips. Ich übernehm das bei gelegenheit in die doku.
Das mit Paypal is nett gemeint, aber es war/ist ein hobby-projekt und ich hab damit python gelernt (und git). Alles gut.
