### ISSUE TITLE
CWL - keine Entities für Luftdurchsatz Zuluft/Abluft

### ISSUE THREAD

**Issue by nanosonde** [marcschmiedchen/home-assistant-wolf_ism8#12]
Hi!

Leider werden in der aktuellen Version für die o.g. Datenpunkte keine Entities mehr angelegt.
Wenn ich das im Code richtig sehe, sollte es daran liegen, dass keine gültigen Wertebereiche für die beiden o.g. Datenpunkte (166, 167) im wolf_ism8 Modul hinterlegt sind.

Hier sollte der Bereich 0-500 ausreichen.
Die CWL400 Excellent geht bis 300m3/h.

**Comment by Dark-Tower-Coder** [comment]
Auch von mir ein Hallo.

Mir fehlen auch die beiden Entitäten für den Durchsatz (Abluft&Zuluft).

@nanosonde 
Welche Stelle im Code meinst du? ->     "DPT_FlowRate_m3/h": (_-2147483647, 2147483647,_ int, 1 / 10000, "m3/h", 4)
Konntest du es den bei dir schon erfolgreich testen?

Wenn ja, dann mach doch mal ein PR :-)

Gruß
Tower

**Comment by nanosonde** [comment]
Hier fehlen zwei Einträge:

https://github.com/marcschmiedchen/wolf_ism8/blob/9b012134141ef9537f27115d0fc3ae89efe832e6/wolf_ism8/ism8_constants.py#L303

**Comment by nanosonde** [comment]
Mhmm. Sorry, habe gerade erst gesehen, dass das nur Validierung der Daten betrifft, die an einen DP gesendet werden sollen.

Also weitersuchen....

**Comment by nanosonde** [comment]
So. Ich habe den Log-Level auf DEBUG gesetzt und sehe nun folgendes Problem:

```
2023-03-07 19:41:18.194 DEBUG (MainThread) [wolf_ism8.ism8] Processing DP-ID 166, Durchsatz Zuluft, message: 00:08:3d:60
2023-03-07 19:41:18.194 DEBUG (MainThread) [wolf_ism8.ism8] datatype not implemented, using INT: DPT_FlowRate_m3/h
2023-03-07 19:41:55.420 DEBUG (MainThread) [wolf_ism8.ism8] Processing DP-ID 166, Durchsatz Zuluft, message: 00:07:7a:10
2023-03-07 19:41:55.420 DEBUG (MainThread) [wolf_ism8.ism8] datatype not implemented, using INT: DPT_FlowRate_m3/h 
```

configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.wolf: debug
    wolf_ism8.ism8: debug
    wolf_ism8.ism8_helper_functions: debug
```

**Comment by nanosonde** [comment]
Sieht so aus, als ob beim Refactoring etwas verloren gegangen ist:
Einmal das hier: https://github.com/marcschmiedchen/wolf_ism8/blob/0ac66e4e96b957575e84cd64ed1dcb4482951eef/wolf_ism8/ism8.py#L348

Und das dann hier: https://github.com/marcschmiedchen/wolf_ism8/blob/0ac66e4e96b957575e84cd64ed1dcb4482951eef/wolf_ism8/ism8.py#L503

**Comment by nanosonde** [comment]
@Dark-Tower-Coder 
Ja genau, jetzt weiß ich auch welche Stelle Du meintest. Du hast recht.
Habe das jetzt alles nachvollzogen.

Es ist schlicht in der Integration nicht implementiert: https://github.com/marcschmiedchen/home-assistant-wolf_ism8/blob/master/custom_components/wolf/sensor.py#L59-L64

Fehlen:
DPT_TIMEOFDAY
DPT_DATE
DPT_FLOWRATE_M3

**Comment by nanosonde** [comment]
Das hier sollte benutzt werden als unit: https://github.com/home-assistant/core/pull/84310/files

**Comment by marcschmiedchen** [comment]
Oh mein erster Pull Request!
Ich hab es mal ungetestet ge-merged -- aber ich kann es hatl nicht testen da ich keine CWL habe.

**Comment by nanosonde** [comment]
Ich habe den Code bei mir im Produktivsystem laufen. Bisher keine Probleme.

**Comment by Dark-Tower-Coder** [comment]
Bei mir scheint es nicht zu funktionieren...

Ich habe erstmal unter "Einstellungen -> Geräte" den Adapter gelöscht. Dann unter "HACS -> Integration" das Packet gelöscht. Danach
-> Neustart
-> "HACS -> Integration" das Packet installiert
-> Neustart
-> "Einstellungen -> Geräte" den Adapter eingerichtet.

Die Entitäten "Zuluft & Abluft" sind jetzt nicht dazu gekommen und ein paar Entitäten zeigen jetzt keine Werte mehr an. Z.B. "Ablufttemperatur".

In den Logs finde ich auch absolut keine Hinweise dazu. Also da wird nichts zu "166/167" oder "Zuluft/Abluft" gelogt.
Habe dazu @nanosonde deine oben gezeigten Einstellungen in die configuration.yaml geschrieben.

Eine Idee woran es liegen könnte?

**Comment by Dark-Tower-Coder** [comment]
Ich konnte das Problem finden.
Anscheinend wurden bei mir nicht die neuen Dateien von github geladen.

Habe die Veränderungen jetzt manuell kopiert und es läuft.

Werde mal die Ursache suchen, weshalb die neuen Daten nicht geladen wurden.

Vielen Dank für die Anpassungen :-)
