### ISSUE TITLE
Warmwassersolltemperatur DP ID 56 keine Eingabe möglich

### ISSUE THREAD

**Issue by stephangeiger1** [marcschmiedchen/home-assistant-wolf_ism8#18]
Hallo Marcschmiedchen,

vielen Dank für die geleistete Arbeit.
Datenpunkt 56, Warmwassersolltemperatur ist nicht als Inputvariable vorhanden. (Ebenfalls 69, 82, 95)
Hier sollte eine Eingabe lt Wolf ISM 8 Doku eine absoutangabe von 20°C bis 80°C möglich sein.

Gruß Stephan

**Comment by marcschmiedchen** [comment]
Neue Version 3.0 kann das jetzt
