### ISSUE TITLE
Sollwertkorrektur/Sparfaktor - Aktueller Wert nicht angezeigt/Wert nicht änderbar

### ISSUE THREAD

**Issue by lzier** [marcschmiedchen/home-assistant-wolf_ism8#19]
Bei Sollwertkorrektur/Sparfaktor gibt es 2 Probleme:
(1) Aktueller Wert wird nicht angezeigt
2) Wert kann nicht geändert werden
Fehlermeldung:
Fehler beim Aufrufen des Dienstes select/select_option. Option -1 not valid for select.dkw_sollwertkorrektur

DPT_TEMPD ist float und muss für die Benutzung von homeassistant.select in str umgewandelt werden.
Die Gegenrichtung in async_select_option gibt es ja schon: option = float(option)
https://developers.home-assistant.io/docs/core/entity/select/
Name    Type    Default Description
current_option  str     None    The current select option
options list    Required        A list of available options as strings

Möglicher Fix:
select.py
class WolfSelect(SelectEntity):
    @property
    def options(self):
        """Return all available options"""

        _options = []
        if self._type in (SensorType.DPT_HVACCONTRMODE,
                          SensorType.DPT_HVACMODE,
                          SensorType.DPT_DHWMODE,
                          SensorType.DPT_TEMPD,
                          SensorType.DPT_SWITCH):

            for opt in self._ism8.get_value_area(self.dp_nbr):
                if self._type == SensorType.DPT_TEMPD:
                    opt = str(opt)
                _options.append(opt)
        else:
            _LOGGER.error("Unknown datapoint type %s for select sensor", self._type)
        return _options

    async def async_update(self) -> None:
        """Return state"""
        option = self._ism8.read(self.dp_nbr)
        if self._type == SensorType.DPT_TEMPD:
            option = str(option)
        self._attr_current_option = option
        return

**Comment by marcschmiedchen** [comment]
behoben.
