### ISSUE TITLE
Send command to update all datapoints after connection was made

### ISSUE THREAD

**Issue by nanosonde** [marcschmiedchen/home-assistant-wolf_ism8#2]
Hi!

It would very helpful if the integration would immediately send a request to the ISM8 to send an update for all datapoints.

Same is done here: https://github.com/openhab/openhab-addons/blob/bf5cea09ed271671ed363ec46d17f4ccfcb08649/bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/Server.java#L226

A version in PHP
```php
function request_all_datapoints($msgsock)
{
    /* Send special message to request all datapoints to be sent. */
    $msg = array(0x06, 0x20, 0xF0, 0x80, 0x00, 0x16, 0x04, 0x00, 0x00, 0x00, 0xF0, 0xD0);
    $str = implode(array_map("chr", $msg));
    fwrite($msgsock, $str , strlen($str));
}
```

In the Wolf ISM8 documentation PDF this mentioned in chapter 8.5 ("Aktives Auslesen der Datenpunkte").

**Comment by marcschmiedchen** [comment]
I Implemented the feature; justu upgrade the wolf-ism8 library. It automatically requests all DP when a connection to the ISM8 is first established.
