### ISSUE TITLE
Datentyp für AN/ AUS - Steuerelemente ungültig

### ISSUE THREAD

**Issue by hwilma** [marcschmiedchen/home-assistant-wolf_ism8#21]
Hallo marcschmiedchen,

Ich habe die Integration komplett neu hinzugefügt. 
Beim Setzen der Werte für die betreffenden Datenpunkte bekomme ich nun folgende Fehlermedlung. Die Fehlermeldung hatte ich bereits im Issue #15 bekommen:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: wolf_ism8.ism8_helper_functions
Source: custom_components/wolf/select.py:137
Integration: Wolf Climate Control ISM8 (documentation, issues)
First occurred: 20:57:29 (3 occurrences)
Last logged: 21:08:54

value for 153 has invalid datatype <class 'str'>, should be <class 'int'>
value for 158 has invalid datatype <class 'str'>, should be <class 'int'>

Vielen Dank für die Bemühungen.

![image](https://user-images.githubusercontent.com/72350299/226729939-7fa1bd7f-5d40-4161-8f21-ae46a3c193f6.png)

![image](https://user-images.githubusercontent.com/72350299/226728549-3d4399b6-f795-4798-9813-759362a86e44.png)
![image](https://user-images.githubusercontent.com/72350299/226730130-a2e40dc7-7ecd-497e-aac9-d8c759071f42.png)

**Comment by marcschmiedchen** [comment]
Bitte nochmal checken. Sorry fürs Betatesting, aber ich habe halt keine CWL zum Testen.....

**Comment by hwilma** [comment]
Ich unterstütze hier gerne als Beta Tester. Habe ja auch einen großen Mehrwert von der funktionierenden Integration.

Der Parameter "Ein" für das zeitweise Intensivlüften und den Feuchteschutz kann man nun setzen.

Das Deaktivieren, also die Übertragung des Wertes "0", führt jdeoch nicht zum deaktivierendes jeweiligen Modus in der Anlage.

Ich habe eine Fehlermeldung erhalten, bei der ich mir nicht zu 100% sicher bin, ob diese im direkten Zusammenhang mit der fehlgeschlagenen Übertragung der "0" steht. Die Meldung wird nur sporadisch, aber immer beim Schreiben eines Wertes ("Ein" oder "Aus") gesetzt.
Darüber hinaus habe ich beobachtet, dass die Auswahl, die Ich treffe nicht immer zu dem passt, was auch zur CWL übermittelt wird. Ich habe beispielsweise gerade den Wert "0" für "zeitweise Intensivlüften" gesetzt, damit wurde jedoch in der Anlage der Modus aktiviert. Das Phänomen ist nicht zu 100% reproduzierbar, ist mir jedoch bereits auch bei dem Parameter für die Betriebsart aufgefallen. Ich habe zum Beispiel "Auto" ausgewählt und der Modus "Comfort" wird aktiviert. Auch hier leider nicht verlässlich reproduzierbar.

Folgende Meldung habe ich erhalten:

Logger: frontend.js.latest.202303091
Source: components/system_log/__init__.py:254
First occurred: 14:31:36 (6 occurrences)
Last logged: 22:13:25

    :0:0 ResizeObserver loop completed with undelivered notifications.
    :0:0 Script error.

**Comment by marcschmiedchen** [comment]
1) haha: wer findet den fehler:

def encode_Bool(input: bool) -> bytearray:
    return bytearray(b"\x01") if input==1 else bytearray(b"\x01")

D.h. egal was man auswählt, es wird immer AN geschaltet in der Library. Also die fehlerbeschreibung passt. Ich reparier es in der Lib. 

2)Der lOg-Eintrag ist ein bekanntes Home-Assistant Frontend Problem, hat nichts mit uns zu tun.

**Comment by marcschmiedchen** [comment]
Fehler mit dem An/aus is behoben. 

Dass er die Betriebsart nicht korrekt entgegennimmt, kann ich aber nicht reproduzieren -- bei mir klappt das, sowohl am Heizkreis als auch beim Warmwasser.  Bitte nochmal genz genau checken. Bitte auch sicherstellen, dass Du nach dem Einstellen entweder lange genug wartest, und/oder die Daten nochmal neu vom ISM8 anforderst. Denn ein reines Senden heisst noch nicht, dass er den Wert in HA auch gleich wieder empfängt. Das dauert, bis der Datenpunkt von der ISM wieder uebers Netzwerk zurück kommt und das kann durchaus 1min später sein.  Einfachste Möglichkeit wäre, es zu senden und dann am Gerät zu gucken, ob sich der Modus geändert hat.
