### ISSUE TITLE
Fehlende Entität Betriebsmodus

### ISSUE THREAD

**Issue by moonGbox** [marcschmiedchen/home-assistant-wolf_ism8#22]
Ich finde leider keine Entität, die den Betriebsmodus (hvaccontrmode) der Wärmepumpe anzeigt (z.B. „Kühlen“). Ich steige gerade von ioBroker zu Home Assistant um und benötige die Entität, um auch meine Raum-Thermostate in den Kühlmodus zu versetzen.

**Comment by marcschmiedchen** [comment]
Hi,
das müsste laut ISM8-Doku Datenpunkt 177, "betriebsmodus" der BWL/CHA sein.... implementiert ist es jedenfalls.
ich hab leider keine waermepumpe. Gibts irgendwelche Log-Einträge oder Fehlder? Kann jemand mit einer Wärmepumpe dem Kollegen helfen?

**Comment by marcschmiedchen** [comment]
hat sich hoffentlich gelöst also
