### ISSUE TITLE
Support for Wolf CHA 07/10?

### ISSUE THREAD

**Issue by andreas-bulling** [marcschmiedchen/home-assistant-wolf_ism8#23]
Doe the code also support CHA X version heat pumps? Or does it support whatever the ISM8 supports? If not then I'd like to suggest to add such support. Thanks!

**Comment by marcschmiedchen** [comment]
Right, it supports, whatever ISM8 supports and is documented in the official API spec from wolf:
https://www.wolf-heiztechnik.at/download/?file=4252.pdf

CHA is explicitly listed in the docs, with datapoints 176-191 for example. So ... that should work.
