### ISSUE TITLE
Alle Werte stehen auf None

### ISSUE THREAD

**Issue by davidka** [marcschmiedchen/home-assistant-wolf_ism8#25]
Die Verbindung zu meinem ISM8i an der BWL-1s Wärmepumpe scheint erfolgreich etabliert zu sein. Am Anfang stehen die Werte auf Unbekannt und springen nach kurzer Zeit auf None.

<img width="329" alt="Screenshot 2023-11-07 at 17 30 33" src="https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/1681446/fbdbcfd8-f4f8-4b32-97c9-1dc113aaa708">

Muss ich noch irgendwo etwas konfigurieren?

**Comment by davidka** [comment]
Hat sich auf wundersame Weise irgendwie von selbst gelöst.

**Comment by marcschmiedchen** [comment]
optimal das
