### ISSUE TITLE
Fehlerhafte Datenpunkte

### ISSUE THREAD

**Issue by bhuddah** [marcschmiedchen/home-assistant-wolf_ism8#26]
Ich beobachte zeitweise fehlerhafte Datenpunkte weit ausserhalb der erwarteten Skala. (6000kW Heizleistung ...)

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/1134116/7e3f05c7-1035-4fdb-b3ae-e3ffb58e7247)

**Comment by bhuddah** [comment]
Um mal noch ein paar Details zu liefern:
Das scheint mit dem Abtauvorgang der Wärmepumpe zu tun zu haben. Eventuell sind das "negative" Werte, die nicht richtig übersetzt werden.

**Comment by marcschmiedchen** [comment]
IN den Docs hab ich folgendes gefunden: 
For all Datapoint Types 9.xxx, the encoded value 7FFFh shall always be used to 
denote invalid data
Ich schätze mal, dass da also "invalid" Daten kommen. Da ich das überlesen hatte, fange ich es in der Library nicht als Fehler ab. Ist nur so eine Vermutung. Ich werd das mal abfangen in naher zukunft. Witzig. Wenn sie schon wissen, dass die Daten falsch sind, koennten sie sie ja auch vielleicht einfach NICHT schicken ?!!

**Comment by marcschmiedchen** [comment]
Hab das "blind" abgefangen. Bitte Feedback ob der Fehler jetzt weg ist.

**Comment by bhuddah** [comment]
fehler tritt leider weiterhin auf:
![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/1134116/8ad47725-438d-4092-89ed-cbec87b73597)

**Comment by marcschmiedchen** [comment]
Wie hast du die neue Version installiert? von Hand oder per HACS? Kompletten Neustart nicht vergessen? wenn alles nix hilft, trag mal bitte in die "configuration.yaml" folgendes ein:

.--------------
logger:
  default: warning
  logs:
    wolf_ism8.ism8: debug
---------------

dann loggt er die werte mit, die er übers netzwerk empfängt. Und dann bitte mal das zu mir schicken, was er als Message kriegt./umrechnet.  Ich kann das leider bei mir nicht nachstellen, scheint nur die CWL zu machen

**Comment by marcschmiedchen** [comment]
achtung, github hat die einrückungen gelöscht. so muss es aussehen

logger:
<tab>default: warning
<tab>logs:
<2xtab>wolf_ism8.ism8: debug

**Comment by marcschmiedchen** [comment]
arrgh ich werde verrückt diese Markdown

logger:
-->einfache einrueckung: default: warning
-->einfache einrueckung: logs:
-->doppelte einrueckung :  wolf_ism8.ism8: debug

**Comment by bhuddah** [comment]
ich hab das jetzt folgendermaßen konfiguriert:

```
logger:
  default: warning
  logs:
    wolf_ism8.ism8: debug
```
werde mich melden, sobald ich logs mit werten habe

**Comment by bhuddah** [comment]
Die Datenpunkte sehen folgendermaßen aus:
```
2024-01-19 14:10:52.766 DEBUG (MainThread) [wolf_ism8.ism8] Processing DP-ID 178,Heizleistung,message: 4c:ff
2024-01-19 14:10:52.766 DEBUG (MainThread) [wolf_ism8.ism8] decoded 19711 to 6548.4800000000005
```

**Comment by marcschmiedchen** [comment]
Ich hab die Implementierung der float-decoder nochmal gecheckt -- sie scheint zu stimmen.
4c:ff sind binär 0100110011111111. Das Vorzeichen ist +, der exponent 1001 , das ergibt 9 und 10011111111 sind 1279. 
nach der WOlf-Spec sind das dann 0.01*1279*2exp9=6548 kW

ist es immer derselbe wert 4c:ff oder kommen auch andere? ich könnte 4c:ff einfach unterdrücken evtl.

**Comment by bhuddah** [comment]
hab noch was cooles gefunden:
```
2024-01-25 13:42:05.679 DEBUG (MainThread) [wolf_ism8.ism8] Processing DP-ID 183,Warmwassertemperatur,message: 00:00
2024-01-25 13:42:05.679 DEBUG (MainThread) [wolf_ism8.ism8] decoded 0 to 0.0
```
safe to say... das warmwasser war nicht null grad. vermutlich ist das auch ein nichtzulässiger wert oder so...

**Comment by hwilma** [comment]
Habe auch in den letzten Tagen vereinzelt fehlerhafte Datenpunkte festgestellt. Leider htte ichvzu dem Zeitpunkt das Loglevel noch nicht angepasst daher nur Screenshots.

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/72350299/5175c917-d57a-4297-a694-6dd5842aae19)
![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/72350299/981f320c-cb7c-4391-9da9-5778196d6d7c)
![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/72350299/1e9c98dd-d40e-45c0-a983-77150ddf4dba)

**Comment by bhuddah** [comment]
Falls das ausschliessen einer konkreten Liste an Fehlkodierungen nicht ökonomisch erscheint, wäre das mmn. auch eine mögliche Strategie. Für mich zur Zielerreichung auf jeden Fall ausreichend.
Es würde leider nicht die gelegentlichen 00:00-Fehler rausfiltern, aber dafür habe ich (ausser dem Ignorieren von GENAU 0, auch keine Lösungsidee.

**Comment by bhuddah** [comment]
Sieht soweit gut aus. Die Fehler mit den Extremwerten sind weg. einzelne verbleibende 00:00-Werte sind wohl was tieferliegendes. Keine Idee, was man da noch machen könnte, ausser die auch zu ignorieren...
Vielen Dank für deinen Einsatz!
