### ISSUE TITLE
Keine Werte

### ISSUE THREAD

**Issue by Dalmapalma** [marcschmiedchen/home-assistant-wolf_ism8#27]
Bei der Konfiguration ist mir aufgefallen, dass bei den Sensoren nichts angezeigt wird. Zum Beispiel steht bei HG1_Abgastemperatur "None °C"...Eigentlich bei sämtlichen Sensoren. Einzig Sensoren mit An/Aus werden korrekt dargestellt (z.B. HG1_Status_Brenner)

**Comment by marcschmiedchen** [comment]
Ist das Problem noch akut? Ohne genauere Beschreibung kann ich nichts dazu sagen, ich hab noch nie was derartiges gehört. Die Werte kommen erst, wenn das ISM8 etwas sendet, das kann bis zu minuten dauern, bzw. bis sich temperaturen ändern. Vielleicht mal ein/aus an der Heizung?
