### ISSUE TITLE
 BM2: Bedienmodul BM2 - Wurde ausgewählt, aber nicht als Gerät angezeigt.

### ISSUE THREAD

**Issue by LHBL2003** [marcschmiedchen/home-assistant-wolf_ism8#29]
Hallo @marcschmiedchen, danke für die Integration. Ich hoffe Deutsch ist ok, da ich die Vermutung habe, dass Schmiedchen aus Deutschland kommt ;)

Ich benutze FHEM und ioBroker und prüfe gerade, ob ich auf HomeAssistant umsteigen kann.
Dabei ist mir natürlich meine Wolf Heizung wichtig. Momentan läuft mein Testaufbau auf einem Raspberry Pi5, den ich mir extra für HomeAssistant gekauft habe. Das Interesse an der Integration ist also groß ;)

----------------------------------------------------------------------------------
**Erfahrungswert vielleicht für andere interessant: Weitere Geräte erweitern, mit kleiner Hürde**

**Meldung "ISM8 - Kein Gerät oder Entitäten - Fehler beim EInrichten"**

Die Einbindung hat auf Anhieb funktioniert, auch wenn ich zur Erweiterung der Geräte (SM1, MM1) alle Geräte einmal löschen und neu anlegen muss, sowie die YAML-Konfiguration überprüfen und den HomeAssistant auch dort neu starten muss.
![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/4a731424-aabb-475a-8da1-8e5c6fd063b1)

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/345e3294-193c-47dc-bb92-7a30e663950c)

----------------------------------------------------------------------------------
 **Mein aktuelles Problem: BM2 - Bediengerät 2 / Bedienmodul 2 wird nicht aufgelistet**

Mein aktuelles Problem ist, dass ich BM2 ausgewählt habe, es aber nicht aufgelistet wird. Da es das letzte Gerät ist, hoffe ich, dass es ein Fehler im Programm ist und das letzte Array nicht verarbeitet wird. (Vermutung, habe noch nicht in den Quellcode geschaut)
![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/b06fdcf6-be7b-4f87-9cf6-fb9b43ecaff1)

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/771ba47c-6160-49e3-819c-7b5424ab8d4b)

Ist dies ein Bug oder muss ich noch etwas beachten?

----------------------------------------------------------------------------------
**Allgemeine Frage / Feature Vorschlag: BM2 - Bediengerät 2 / Bedienmodul 2 wird nicht aufgelistet**
 
Und wenn das Bedienmodul vorhanden ist, frage ich mich, ob ich die folgenden Parameter über HomeAssistant steuern kann. Denn unter SYM sehe ich bisher "nur" die Warmwasser Einmalladung.
- Programmwahl Mischer
- Programmwahl Warmwasser
- Sollwertkorrektur
- Einsparfaktor

Die 4 Parameter sind für mich wichtig, da ich derzeit über den ioBrocker meine Heizung bedarfsgerecht steuere. 
z.B.: alle Heizkörper / Fußbodenheizungsventile zu, dann Heizung Standby
oder: Mind. 1 Heizkörper 100% auf, dann mehr Leistung, um den Raum schnell warm zu bekommen.
usw.

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/1bf22536-2d05-4d3b-96e7-166e85be818b)

Vielen Dank für deine Hilfe.

**Comment by LHBL2003** [comment]
Das was ich vom Bedienmodul gesucht habe, befindet sich scheinbar unter. DKW und dort kann man auch die Sachen via Dropdown auswählen. Somit haben sich meine Punkte oben erledigt.

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/c541c58a-6fd6-4388-b3ba-efd0ab8b6bde)

**Comment by JDD-Home** [comment]
OK ich würde das Fass doch noch mal aufmachen.
Warum kann dich BM2 auswählen, wenn es aber gar nicht als Gerät gelistet wird und scheinbar die Dinge von BM2 in anderen Bereichen wie DKW oder SYM wiederzufinden sind?

**Comment by marcschmiedchen** [comment]
Hi,
die Aufteilung richtet sich strikt nach der Wolf-Spezifikation. Muss man googeln, im Moment ist sie auf 
https://www.wolf.eu/de-de/professional/downloads/downloadcenter?selection=ism8
zu finden.

"BM2" kann man auswählen, weil es laut Spec Datenpunkte dazu gibt. Falls die Datenpunkte nicht ankommen, kann das z.B. auch an veralteter Firmware liegen, ich bekomme die Daten bei mir auch nicht... und bei der Sortierung der Dinge habe ich mich streng an die Hersteller-Sortierung gehalten, sonst kommt man nur durcheinander, wenn bspw. jemand von FHEM nach HA umsteigt. So wie es ist, kann man jeden Datenpunkt mit der Wolf-Doku zusammen eindeutig identifizieren....

**Comment by JDD-Home** [comment]
Danke für deine Rückmeldung, dann weiß ich ja das alles passt. Vielen Dank für deine mühe. :)
