### ISSUE TITLE
Implement DPT_FlowRate for CWL

### ISSUE THREAD

**Issue by nanosonde** [marcschmiedchen/home-assistant-wolf_ism8#3]
DPT_FlowRate decoder in PHP:

```php
function convfrom_DPT_FlowRate($val)
{
	$value = ($val[0]<<24)|($val[1]<<16)|($val[2]<<8)|($val[3]<<0);
	$flowrate = $value * 0.0001;
	return ((string)$flowrate);
}
```

Do you have any plan to support these? At least for reading?

```
 Logger: wolf_ism8.ism8
Source: /usr/local/lib/python3.9/site-packages/wolf_ism8/ism8.py:494
First occurred: 13:31:33 (10 occurrences)
Last logged: 13:31:36

    datatype not implemented: DPT_Date
    datatype not implemented: DPT_TimeOfDay
    datatype not implemented: DPT_FlowRate_m3/h
```

BTW: Where can I find the repo for the wolf_ism8 python module?

**Comment by marcschmiedchen** [comment]
Tried to implement it.  Issue moved to wolf-ism8 library. Please check for functionality and report back.

**Comment by nanosonde** [comment]
Hi!
Stupid question, but how do I just update the wolf_ism8 module. The custom component did not change or require a newer version of it.
I am using HASS OS.

**Comment by nanosonde** [comment]
@marcschmiedchen 

The flowrate is now shown. The value is correct, but the unit of measurement is wrong.
Home Assistant shows "ccm/h". This is wrong. It is supposed to be  "m3/h".
