### ISSUE TITLE
Feature Request: Gerätenamen ausschreiben wie auch beim Geräteanlegen.

### ISSUE THREAD

**Issue by LHBL2003** [marcschmiedchen/home-assistant-wolf_ism8#30]
Bitte die Gerätenamen ausschreiben, so wie sie in der Auswahl beim Anlegen erscheinen.
Gerade wenn man nicht jeden Tag in den Bereichen ist oder Neuling ist, vergisst man schnell die Abkürzungen.
Zumal diese teilweise anders heißen als die Originalbezeichnungen von Wolf.

Beispiel DKW (Direkter Heizkreis/WW) welches scheinbar viele Dinge enthält, welche bei Wolf unter (BM1 / BM2) Bedienmodul 1 / 2 gelistet werden.

![image](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/2ec517d3-604f-4661-870e-c794f076eeae)

**Comment by marcschmiedchen** [comment]
umgesetzt
