### ISSUE TITLE
Unkown Datapoints

### ISSUE THREAD

**Issue by Vainac86** [marcschmiedchen/home-assistant-wolf_ism8#31]
Moin, ich habe in den HA Protokollen folgende Fehler:

ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 336, data:bytearray(b'\x00')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 362, data:bytearray(b'\x00')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 363, data:bytearray(b'\x00')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 337, data:bytearray(b'\x03')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 338, data:bytearray(b'\x01')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 341, data:bytearray(b'\x00')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 339, data:bytearray(b'\x00')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 340, data:bytearray(b'\x01')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 342, data:bytearray(b'\x01')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 343, data:bytearray(b'\x01')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 344, data:bytearray(b'\x01^')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 345, data:bytearray(b'\x03\x84')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 347, data:bytearray(b'\x01')
ERROR (MainThread) [wolf_ism8.ism8] unknown datapoint: 348, data:bytearray(b'\x01')

Heizung: Wolf CHA07-200

Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

**Comment by marcschmiedchen** [comment]
sollten jetzt keine fehler mehr werfen
