### ISSUE TITLE
Programmauswahl Heizkreis, Warmwasser wird gesetzt aber falsch in HA dargestellt.

### ISSUE THREAD

**Issue by LHBL2003** [marcschmiedchen/home-assistant-wolf_ism8#36]
Ich kann die Programmauswahl Heizkreis und Warmwasser an die Wolf Heizung übertragen. Aber nach Auswahl wird mir weiterhin der falsche Status in HA angezeigt. Auch nach ein Regenschirm der App oder im Browser steht nicht das was in der Heizung gesetzt ist. 

![IMG_9407](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/0dad0285-cabf-4189-a2dd-66106942c850)
![IMG_9406](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/f1a7bcc7-4a08-43c6-9d85-20362f189485)

![IMG_9405](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/d6397379-3335-4d4f-99da-18e56d3a8838)

**Comment by marcschmiedchen** [comment]
Hi, das problem kann ich leider nicht replizieren. 
Ich war grade im Keller, hab etwas verstellt und sowohl Heizkreis als auch Warmwasserprogramm updaten sich danach in HA. Allerdings musste ich explizit die Seite im Browser neu laden.
=> bitte nochmal checken mit der neuen Version (3.0.1, die kommt bald)

**Comment by LHBL2003** [comment]
Verstell mal bitte etwas in HA. Es wird in der Heizung ankommen, aber nach einem Refresh von der HA Seite wird es in HA nicht mehr passen. Bei mir steht dann spätestens wieder der alte Wert dort, obwohl es in der Heizung angekommen ist.

**Comment by LHBL2003** [comment]
Hallo @marcschmiedchen ,

Also ich bin auch nochmal in den Keller gegangen :D 
Ich habe an der Wolf Heizung auf der Seite "Heizkreis" und "Warmwasser" geprüft, ob diese im Automatikbetrieb sind. Warmwasser hatte ich gestern wohl vergessen. Zum Glück haben wir einen Kamin :D
Demzufolge habe ich Warmwasser in den Modus "Automatikbetrieb" geändert.
Home Assistant zeigte nach ca. 1 Minute auch für Warmwasser den Status "Auto" an.

In HA ist nun im Bereich "Direkter_Heizkreis_WW" die "Programmauswahl Warmwasser" und "Programmauswahl Heizkreis" auf "Auto".

Danach habe ich beides in HA auf Standby gesetzt.
Ein paar Sekunden später stand in HA immer noch "Standby".
Nach einem Refresh des Browsers stand in beiden Feldern aber wieder "Auto".
Die Wolf Heizung hat wie erwartet für den Heizkreis und das Warmwasser auf "Standby" umgeschaltet.
In der HA Visu bleibt es jedoch auch nach 2-3 Minuten im falschen Zustand "Auto".

Vielleicht hilft dir das zum Nachstellen des Fehlers. :)

**Comment by marcschmiedchen** [comment]
OK, war schwer zu finden. Ein Cache-Problem. Sollte jetzt passen (in 3.0.1)

**Comment by LHBL2003** [comment]
Funktioniert wie ein Schweißer Uhrwerk Danke schön ;-)
