### ISSUE TITLE
Pressure change pa to bar

### ISSUE THREAD

**Issue by RFA81** [marcschmiedchen/home-assistant-wolf_ism8#39]
Hello, i want to change the pressure from pa to bar. i tried to change the unit of measurement on the entity but it is not working.

**Comment by marcschmiedchen** [comment]
Switching units "on the fly" cant be done in HA, as far as i know. Usually, people create a "template Sensor". Google is your friend. , or try for example:

https://blog.stefandroid.com/2022/10/29/home-assistant-unit-conversion.html

**Comment by marcschmiedchen** [comment]
RFA81 was right in the first place, my integration prohibited the changes of unit in the FrontEnd. I'll fix it.

**Comment by marcschmiedchen** [comment]
done.
