### ISSUE TITLE
cannot find in HACS store

### ISSUE THREAD

**Issue by gasinkas** [marcschmiedchen/home-assistant-wolf_ism8#42]
Hi, I'm unable to find the HACS integration when I search something with "wolf". Do i have to add anything anywhere?

Core 2024.4.0 (also not visible in 2024.3.0)
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240403.1

Best regards,
Stefan

**Comment by marcschmiedchen** [comment]
no, should be right there.
If you updated /reinstalled stuff, maybe wait for a day or so, since the HACS integration needs to scan all the repositories, I guess.
Anybody else having issues with HACS?

**Comment by gasinkas** [comment]
Here's my view on the HACS search: 

![grafik](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/66009866/bcbae82e-3ccb-43c5-b24e-85da935eb0d3)

**Comment by gasinkas** [comment]
Sorry, my bad. Thanks for adding that information :)
