### ISSUE TITLE
I think there is something wrong with the error status of the entities.

### ISSUE THREAD

**Issue by LHBL2003** [marcschmiedchen/home-assistant-wolf_ism8#45]
EN:
From a current perspective, I would say that faults are displayed correctly but do not work properly.
For example, if I close the gas valve and restart the heating, I get the message "Problem" for the heater1 fault.

However, if I now create an automation by using the entity "binary_sensor.heizgeraet1_stoerung" as a trigger. (change to "Problem"), the automation is still not started. 
Even if I create a group helper to summarise all faults, this does not react.

I have built a binary_sensor template helper for printing, which is also of the display type Problem. This triggers the automation and also changes the status in my helper group.

DE:
Aus aktueller Sicht würde ich sagen, dass Störungen zwar richtig angezeigt werden, aber nicht richtig arbeiten.
Wenn ich z.B. das Gasventil schließe und die Heizung neu starte, dann bekomme ich als Meldung für das Heizgerät1 Störung „Problem“.

Wenn ich nun aber eine Automatisierung erstelle, indem ich die Entität „binary_sensor.heizgeraet1_stoerung“ als Trigger verwende. (Wechsel zu „Problem“) So wird dennoch die Automatisierung nicht gestartet. 
Auch wenn ich einen Gruppen Helfer erstelle um alle Störungen zusammenzufassen reagiert dieser nicht.

Ich habe mir für den Druck ein binary_sensor Template Helfer gebaut, der auch vom Anzeigetyp Problem ist. Dieser Triggert die Automatisierung und ändert auch in meiner Helfergruppe den Status.

**Zusammenfassung:**
- Wenn man zwei Störungen in einer Helfer Gruppe zusammenfasst. So bleibt der Status immer OK. Auch wenn ein „Problem“ ausgelöst wurde.
- Wenn man eine Störungs Entität in einer Automatisierung verwendet und auf Status Änderung zu „Problem“ so wird diese nicht ausgelöst.
- Eine selbst erstellter Helfer Template Status wechselt in der Kachel Ansicht zu Problem und Ändert das Icon von einem grauen Haken zu einem Roten Ausrufezeichen. Die Wolf Integration bleibt immer bei einem gelben Haken.

![IMG_0003](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/6120f1ed-63ec-405d-92cd-7ff50f61d493)
![IMG_0004](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/79475eab-5f78-4e04-a653-100d1eeabc09)
![IMG_0005](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/cb5226c2-6a42-41aa-9921-22fa792ea5b7)
![IMG_0006](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/88ed2b3f-f0d0-4df7-8dfd-f25384afb021)
![IMG_0007](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/3aa4656b-a275-4fce-9385-54e023951694)
![IMG_0008](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/41b6fffe-44d2-490a-bfcf-e34ffd95f250)
![IMG_0009](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/969af06c-ab79-4d75-898a-abb4a696fe39)
![IMG_0010](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/ae777990-0ed3-4b1c-a79d-966e868ceee1)
![IMG_0011](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/09db9a5a-ac59-418f-999f-afdad0d3984c)
![IMG_0012](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/759a55e0-8433-44f3-af63-e6579c9053e5)
![IMG_0014](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/889172cb-e1c2-4728-ba50-61dcfa00bc7e)
![IMG_0015](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/ccea0a12-e708-4f33-a515-ec502b3702a9)

**Comment by marcschmiedchen** [comment]
Should be fixed, but I cannot test it. Please test the issue with the latest version (3.0.2) and close it if errors are gone.

**Comment by LHBL2003** [comment]
Unfortunately, the sun shines too often, so the burner doesn't start even after the heating system is restarted. Instead, the mixer briefly reported an error and also sent a push message to the mobile phone. The icon now also fits. See Mischer Icon in Picture 

So I would say it works :)
Thank you. 

![IMG_0587](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/46369917/4f391b9d-4897-4c4c-89cd-a5666d82ec38)
