### ISSUE TITLE
CWL - available programs

### ISSUE THREAD

**Issue by gkressel** [marcschmiedchen/home-assistant-wolf_ism8#48]
Hi,

I've found a minor issue with the CWL programs in version 3.0.2.

It's possible to select the programs “Automatikbetrieb”, “Nennlüftung”, ”Red. Lüftung”, and “Feuchteschutz.” However, the WOLF documentation is a bit confusing on this topic because, according to the datapoint definitions, these types are available:
![grafik](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/88251998/1a755ab2-0809-4860-8620-0ce21b92f8b0)

But only 0, 1, and 3 are matched to corresponding programs on the CWL.
![grafik](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/88251998/6f4f245d-4d41-4f15-a74e-c9631a5c6fe1)

According to WOLF's specifications, please remove the “Feuchteschutz” option, as it is not working and may cause confusion.

Thank you in advance!

**Comment by marcschmiedchen** [comment]
The documentation is indeed confusing; my interpretation so far was that, you cannot explicitly set the device to "Standby" or "Building Protection", but it is possible, that these values are sent from CWL, when the device enters them by itself.

=>I will restrict the supported values to 0,1 and 3.

**Comment by marcschmiedchen** [comment]
please check if the issue still persists

**Comment by gkressel** [comment]
hi @marcschmiedchen,

thanks for picking this up! 

However, the behavior isn't as expected. It appears that selecting "red. Lüftung" is no longer possible. When toggling between the available programs, only "Automatikbetrieb" and "Nennlüftung" are being transmitted to the ism8.
![grafik](https://github.com/marcschmiedchen/home-assistant-wolf_ism8/assets/88251998/5cf6387f-3b8a-40b0-94ac-0154084ed575)

**Comment by marcschmiedchen** [comment]
That is something I cannot replicate.... On my machine, that works just fine.
When I publish the minor updates for the other issue, I will also upload a new version to the library on Pypi, see if that solves the issue. May I had a CWL-specific bug in 3.2. which I "accidentially" fixed on my machine. I would ask you to re-test this issue with the next update.
Sorry for this remote-debugging, but coding is hard against a "ghost" CWL. :)

**Comment by marcschmiedchen** [comment]
Uploaded v.3.2.1. On my machine, setting "Red. Lüftung" is trying to send data ("3") to ISM8. Should be working....

**Comment by gkressel** [comment]
hi @marcschmiedchen,

Yes, it's working perfectly now.
