### ISSUE TITLE
Warning for 2024-07-11 16:34:36.760 WARNING (MainThread) [homeassistant.helpers.frame] Detected code migth not work with Assistant 2025.1

### ISSUE THREAD

**Issue by NorbertMeyer** [marcschmiedchen/home-assistant-wolf_ism8#56]
Let me first say "Thanks a lot" for providing Software and advice how to make use of ISM8 in our new CHA10.

#It took me a day from scratch to get an idea what is needed overall and to get it running on an Docker Desktop instance, after changing the network configuration from "Auto", which was discovered as eth0, to Docker0 fitting better to container running with network=host.

During that I found the following warning in the logfile: 

2024-07-11 16:34:36.760 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration wolf with title: ISM8 and entry_id: 01J2HAB2XJGW129NV7WY8MMG1E, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue. 

Without understanding it (yet), I would like to mention before 2025.1 comes.

Again, Thanks a lot

Best regards

Norbert.Meyer@meyers2web.de

**Comment by marcschmiedchen** [comment]
thanks, I had that on my list already, but this issue will serve as a reminder

**Comment by oaken-source** [comment]
I've just run into the same issue.

**Comment by marcschmiedchen** [comment]
I'm on it

**Comment by marcschmiedchen** [comment]
fixed it

**Comment by NorbertMeyer** [comment]
Thanks a lot. 
 Best regards
Norbert--Gesendet mit der 1&1 Mail AppAm 04.10.24, 11:52 schrieb marcschmiedchen ***@***.***>:

  
  fixed it
