### ISSUE TITLE
Wärmepumpe Steuerung

### ISSUE THREAD

**Issue by Hefti1923** [marcschmiedchen/home-assistant-wolf_ism8#66]
In der Integration gibt es leider keine Möglichkeit etwas an den Einstellungen zu verändern. Außer 1x Warmwasser.

Um eine optimiertere Steuerung in Kombination mit z.B. einer PV-Anlage zu erreichen, wäre es super, wenn man den Betriebsmodus für Heizung bzw. Kühlung über Home Assistent einstellen könnte.

Mit freundlichen Grüßen 
Hefti

**Comment by Vainac86** [comment]
Ich regel das über Home Assistant, welcher bei bestimmter PV Leistung oder Akku Stand eine Shelly 1 schaltet welche den PV Relais Kontakt einer CHA07 umschaltet. 
Das erhöht dann automatisch die Soll Temperaturen.

**Comment by procodix** [comment]
Kann man für eine CHA10 die Stromaufnahme aktuell und Gesamt auslesen?

**Comment by marcschmiedchen** [comment]
Ich kann es nicht sicher sagen, sollte aber. Anbei die Specs vom ISM. Da steht CHA: Datenpunkt 191: Leistungsaufnahme in kW
[ISM8i_09_2022.pdf](https://github.com/user-attachments/files/17606601/ISM8i_09_2022.pdf)

**Comment by marcschmiedchen** [comment]
Dann mach ich das hier mal zu ....
