### ISSUE TITLE
missing statistics for all senors

### ISSUE THREAD

**Issue by AlexJacu** [marcschmiedchen/home-assistant-wolf_ism8#68]
no one of the sensors have a statistic for use in statistic diagram.
in the list of statistic sensors in ha no ism8i senors are listed

**Comment by AlexJacu** [comment]
der Sensor hat die Daten, aber der Rekorder für die Sensoren ist offenbar nicht aktiviert. Hab ich da irgendwo einen fehler gemacht?
![image](https://github.com/user-attachments/assets/84fe1579-8d70-4a44-a418-0aa8343a88b2)
![image](https://github.com/user-attachments/assets/a0bc2c46-4a48-4469-aa02-e4ce57408606)
![image](https://github.com/user-attachments/assets/bb847346-b80c-4755-9ef8-7e15deb13864)

**Comment by marcschmiedchen** [comment]
nein, der fehler liegt tatsächlich in der integration. Da fehlen Infos, ohne die die Statistik nicht aktiviert wird. Bin dran.

**Comment by AlexJacu** [comment]
> nein, der fehler liegt tatsächlich in der integration. Da fehlen Infos, ohne die die Statistik nicht aktiviert wird. Bin dran.

Das wäre echt klasse. Aktuell zeigt HA für die Entitäten nur die letzten 10 Tage an und alles ältere ist verloren.

**Comment by marcschmiedchen** [comment]
fixed that with 4.0 per today
