### ISSUE TITLE
Install error line 52, in async_setup

### ISSUE THREAD

**Issue by katakefalos** [marcschmiedchen/home-assistant-wolf_ism8#9]
Hallo ich hab die Installationsanweisungen befolgt aber bekommt folgenden Fehler beim Starten von Home Assistent:

2022-07-14 22:29:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component wolf
File "/config/custom_components/wolf/__init__.py", line 52, in async_setup

**Comment by nanosonde** [comment]
Welche HA Version benutzt Du?

**Comment by katakefalos** [comment]
Home Assistant 2022.7.5 Supervisor 2022.07.0 Operating System 8.2 Frontend 20220707.1 - latest

**Comment by katakefalos** [comment]
Can someone help? Kann jemand helfen?

**Comment by marcschmiedchen** [comment]
Obwohl ich den Fehler nicht replizieren konnte: die neue Version nutzt den Config-FLow in der GUI. Da sich das Setup damit grundlegend geändert hat, gehe ich mal davon aus dass der Fehler auch nicht mehr existiert. Wenn doch, bitte das Issue mit mehr Details nochmal aufmachen
